### ISSUE TITLE
Seperate priming and retraction speed?

### ISSUE THREAD

**Issue by sumguysr** [shapeforge/icesl-printers#33]
Is there any way to set different priming and retraction speeds as with Cura and the Slic3r family? Inspired by this article I did lots of test printing and found the perfect settings for PETG on my hot end (TriangleLabs Microswiss Clone on a stock Ender 3) to be 55m/s retraction, 15mm/s priming, and 0.3mm z-hop.

https://www.sublimelayers.com/2016/10/some-musings-on-retracts.html

**Comment by Phazon54** [comment]
Hello,

Sorry for the quite late answer...

I have currently implemented this change, and it will be available in the next betas.

In the meanwhile, you can still easily hack a different value for primes and retracts by editing the retract and prime functions of your profile. 
if you do so, you won't be able to edit said values from IceSL's UI until the next betas.
