### ISSUE TITLE
brim_distance_to_print setting ignored

### ISSUE THREAD

**Issue by f1vefour** [shapeforge/icesl-printers#35]
No matter what you put in the features.lua configuration file for the setting `brim_distance_to_print = ` it stays at 1mm when you open the profile in IceSL.

This is been an issue for as along I've used the slicer which is nearly a year

**Comment by Phazon54** [comment]
Hello, and sorry for the late reply.

The correct setting to manage the brim distance is `brim_distance_to_print_mm` (note the `_mm` suffix).

I will do a pass on all the profiles, as it seems that the correct setting name was not propagated correctly to the profiles that are supposed to used this setting.

**Comment by Phazon54** [comment]
Profiles updated with the correct settings in 3bb15c0

**Comment by f1vefour** [comment]
Thanks Pierre, closing issue.
