### ISSUE TITLE
[BUG?] Extruder backwards for stock Artillery Sidewinder X1

### ISSUE THREAD

**Issue by Stitch10925** [shapeforge/icesl-printers#36]
When using the "Artillery_SW_X1" profile on a stock Artillery Sidewinder X1 the extruder is running backwards.

Cure generates extruder code running from 0.x mm to (in my case) 40.x mm. IceSL starts at 40.x mm and goes down to 0.x mm, this causes the extruder to unload filament instead of loading it.

I went through the documentation but I'm not quite sure how to fix/reverse this.

**Comment by Phazon54** [comment]
Hello, there is indeed an issue with the profile shipped with IceSL right now.

You will find attached a fixed profile.
[Artillery_SW_X1.zip](https://github.com/shapeforge/icesl-printers/files/7195210/Artillery_SW_X1.zip)

To install this profile, extract the attached profile into the IceSL's profiles location:
- on Windows in `%appdata%/IceSL/icesl-printers/fff/`
- on Linux, in `[icesl_extracted_location]/icesl/icesl-printers/fff/`

This fixed profile will be included in the next release

**Comment by Stitch10925** [comment]
Hey Pierre,

Thank you for the fast response. The new profile you sent me is working much better!

I am wondering if it would make sense to have a "extruder initialization" phase in the header like Cura
does?

For example, I updated the header to the following:

;=== START HEADER ===
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion

M104 S<TOOLTEMP> ; set temperature
M190 S<HBPTEMP> ; wait for bed temperature to be reached

G28 ; home all axes
G1 X20 Y20 Z20 F10000

M109 S<TOOLTEMP> ; wait for temperature to be reached
M117 Purge extruder
G92 E0 ; reset extruder

G1 Z1.0 F3000 ; move z up little to prevent scratching of surface
G1 X2 Y20 Z0.3 F5000.0 ; move to start-line position
G1 X2 Y200.0 Z0.3 F1500.0 E15 ; draw 1st line
G1 X2 Y200.0 Z0.4 F5000.0 ; move to side a little
G1 X2 Y20 Z0.4 F1500.0 E30 ; draw 2nd line

G92 E0 ; reset extruder
G1 Z1.0 F3000 ; move z up little to prevent scratching of surface
;=== END HEADER ===

I might not need it because I noticed that my first layer may start too high, so I will probably have to recalibrate,
but it did make sure the extruder was clean when starting the first layer since any excess that oozed out of the
extruder during heating has been wiped off.

Sincerely,
Glenn

________________________________

**Comment by Phazon54** [comment]
Hello Glenn,

Since the header of this profile is managed in `header.gcode`, and as long as the "macros" for setting up temperatures (ie `<TOOLTEMP>` are properly used in the `header()` function, in `printer.lua`, you can pretty much put what you want inside !

The current header is minimal here because, as far as I can remember, the original author based this profile on a profile which had this minimal header. 
But, if you think that this is too minimal, you can add on it (like you mentioned), and once you've tested it and happy with the results, you can do a pull request !
